---
author:
  - 'Anatoliy Lapitskiy <nuclon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Class: 0
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Qless
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Class::Load: 0
  Daemon::Generic: 0
  File::ShareDir: 0
  JSON::XS: 0
  Redis: 0
  Time::HiRes: 0
  perl: 5.6.0
version: 0.06
